Models/Enrollment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Labb_2___Linq.Models
{
    public class Enrollment
    {
        [Key]
        public int EnrollmentId { get; set; }
        [ForeignKey("Course")]
        public int FkCourseId { get; set; }
        public Course? Course { get; set; }
        [ForeignKey("Student")]
        public int FkStudentId { get; set; }
        public Student? Student { get; set; }
    }

}

Controllers/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Labb_2___Linq.Data;
using Labb_2___Linq.Models;
using static Labb_2___Linq.Controllers.StudentTeacherViewModel;

namespace Labb_2___Linq.Controllers
{
    public class EnrollmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EnrollmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Enrollments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Enrollments.Include(e => e.Course).Include(e => e.Student);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Enrollments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.EnrollmentId == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // GET: Enrollments/Create
        public IActionResult Create()
        {
            ViewData["FkCourseId"] = new SelectList(_context.Courses, "CourseId", "CourseName");
            ViewData["FkStudentId"] = new SelectList(_context.Students, "StudentId", "LastName");
            return View();
        }

        // POST: Enrollments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EnrollmentId,FkCourseId,FkStudentId")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enrollment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkCourseId"] = new SelectList(_context.Courses, "CourseId", "CourseId", enrollment.FkCourseId);
            ViewData["FkStudentId"] = new SelectList(_context.Students, "StudentId", "LastName", enrollment.FkStudentId);
            return View(enrollment);
        }
        //GET StudentsWithTeachers
        public async Task<IActionResult> StudentsWithTeachers()
        {
            var viewModel = await _context.Enrollments
                .Include(e => e.Student)
                .ThenInclude(s => s.SchoolClass)
                .Include(e => e.Course)
                .ThenInclude(c => c.Teacher)
                .Select(e => new StudentTeacherViewModel
                {
                    StudentName = $"{e.Student.FirstName} {e.Student.LastName}",
                    TeacherName = $"{e.Course.Teacher.FirstName} {e.Course.Teacher.LastName}",
                    CourseName = e.Course.CourseName,
                    ClassName = e.Student.SchoolClass.ClassName
                })
                .ToListAsync();

            return View(viewModel);
        }



        // GET: Enrollments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments.FindAsync(id);
            if (enrollment == null)
            {
                return NotFound();
            }
            ViewData["FkCourseId"] = new SelectList(_context.Courses, "CourseId", "CourseId", enrollment.FkCourseId);
            ViewData["FkStudentId"] = new SelectList(_context.Students, "StudentId", "LastName", enrollment.FkStudentId);
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EnrollmentId,FkCourseId,FkStudentId")] Enrollment enrollment)
        {
            if (id != enrollment.EnrollmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrollmentExists(enrollment.EnrollmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkCourseId"] = new SelectList(_context.Courses, "CourseId", "CourseId", enrollment.FkCourseId);
            ViewData["FkStudentId"] = new SelectList(_context.Students, "StudentId", "LastName", enrollment.FkStudentId);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.EnrollmentId == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enrollment = await _context.Enrollments.FindAsync(id);
            if (enrollment != null)
            {
                _context.Enrollments.Remove(enrollment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnrollmentExists(int id)
        {
            return _context.Enrollments.Any(e => e.EnrollmentId == id);
        }
    }
}

Views/Enrollments/Create.cshtml
@model Labb_2___Linq.Models.Enrollment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Enrollment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FkCourseId" class="control-label"></label>
                <select asp-for="FkCourseId" class ="form-control" asp-items="ViewBag.FkCourseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="FkStudentId" class="control-label"></label>
                <select asp-for="FkStudentId" class ="form-control" asp-items="ViewBag.FkStudentId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Enrollments/Delete.cshtml
@model Labb_2___Linq.Models.Enrollment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.CourseId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EnrollmentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Enrollments/Details.cshtml
@model Labb_2___Linq.Models.Enrollment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.CourseId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.EnrollmentId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Enrollments/Edit.cshtml
@model Labb_2___Linq.Models.Enrollment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Enrollment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EnrollmentId" />
            <div class="form-group">
                <label asp-for="FkCourseId" class="control-label"></label>
                <select asp-for="FkCourseId" class="form-control" asp-items="ViewBag.FkCourseId"></select>
                <span asp-validation-for="FkCourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FkStudentId" class="control-label"></label>
                <select asp-for="FkStudentId" class="form-control" asp-items="ViewBag.FkStudentId"></select>
                <span asp-validation-for="FkStudentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Enrollments/Index.cshtml
@model IEnumerable<Labb_2___Linq.Models.Enrollment>

@{
    ViewData["Title"] = "Index";
}

<h1>Student enrollment</h1>

<p>
    <a asp-action="Create" class="btn btn-success mb-3">Enroll Student</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Student)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Course.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.FirstName)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.EnrollmentId" class="btn btn-info">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.EnrollmentId" class="btn btn-primary">Details</a>
                    <a asp-action="Delete" asp-route-id="@item.EnrollmentId" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<a asp-controller="Enrollments" asp-action="StudentsWithTeachers" asp-route-courseName="Programmering 1" class=" btn btn-primary mt-3">Students and Teacher Courses</a>

Views/Enrollments/StudentsWithTeachers.cshtml
@model IEnumerable<Labb_2___Linq.Controllers.StudentTeacherViewModel>

<h2>Students and their Teachers</h2>

<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>Student</th>
            <th>Teacher</th>
            <th>Course Name</th>
            <th>Class</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.StudentName</td>
                <td>@item.TeacherName</td>
                <td>@item.CourseName</td>
                <td>@item.ClassName</td>
            </tr>
        }
    </tbody>
</table>